---
- name: LDAP Server
  hosts: ldap
  become: true
  
  tasks:
    - name: Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - package

    - name: Install user package
      yum:
        name:
          - mc
          - vim
          - wget
        state: latest
      tags:
        - user-package
        - package

